### ISSUE TITLE
How to replace the Arduino Builder?

### ISSUE THREAD

**Issue by jttaylor86** [BoschSensortec/BSEC-Arduino-library#19]
In the instructions for using the BSEC Arduino Library in Arduino 1.8.5 I don't really know what I am required to do with point 3.

"3. Replace the arduino-builder
The arduino-builder-PR219 now has the ability to select the appropriate pre-compiled library from the library folder.

Replace the arduino-builder executable from the Arduino installation folder with the appropriate file based on your OS from this link arduino-builder-219.zip."

Where is the original arduino-builder executable located and what is it called?

I would appreciate any help.

Thanks,

Justin

**Comment by 523p** [comment]
I have the same problem. Arduino IDE 1.8.8 and no arduino-builder file on whole computer, not even *builder* executable.
