### ISSUE TITLE
warning code : 10

### ISSUE THREAD

**Issue by yukimach** [BoschSensortec/BSEC-Arduino-library#9]
Is there documentation on what the warning code represents? 

I can't locate it to figure out what it means.

**Comment by BoschSensortec** [comment]
@yukimach,

What warning code do you get??

**Comment by BoschSensortec** [comment]
Hi @yukimach,

BSEC error codes can be found [here](https://github.com/BoschSensortec/BSEC-Arduino-library/blob/0255bd177335e9ac3557c30193b98ceac4cd564b/src/inc/bsec_datatypes.h#L282) and BME680 error codes can be found [here](https://github.com/BoschSensortec/BSEC-Arduino-library/blob/0255bd177335e9ac3557c30193b98ceac4cd564b/src/bme680/bme680_defs.h#L131).

The error you are receiving is a BSEC warning code

>  BSEC_W_SU_UNKNOWNOUTPUTGATE = 10, /*!< Output (virtual) sensor id passed to bsec_update_subscription() is not in the valid range; e.g., n_requested_virtual_sensors > actual number of output (virtual) sensors requested */

Can you describe your call to updateSubscription?

**Comment by BoschSensortec** [comment]
Hi @yukimach,

Can you try with the latest version of the library 1.4.6.0?

**Comment by yukimach** [comment]
Ok, looking into it. I've got the latest commit. library.properties file indicate 1.4.6.0 and when I check on arduino manage libraries it is also 1.4.6.0. Not sure why so I'm digging into it but if you have any thoughts on why this might be please let me know.

**Comment by yukimach** [comment]
I had the previous libalgobsec. followed the new install set up and its all good now with no warning.
Thanks.
